name: Publish Drafted GitHub Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  publish_release_draft:
    runs-on: ubuntu-latest
    if: github.repository == 'jellyfin/jellyfin-plugin-pushbullet'
    
    steps:
      - name: Get version from GITHUB_REF
        id: get-version
        run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"

      - name: Publish release on GitHub
        uses: test-room-7/action-publish-release-drafts@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-name: ${{ steps.get-version.outputs.version }}
